### ISSUE TITLE
TODO for the workshop

### ISSUE THREAD

**Issue by yalinli2** [QSD-Group/QSDsan-workshop#1]
TODO list for the workshop on April 22, 2022:
- [x] Create three Jupyter Notebook examples
    - [x] one is the full populated workbook
    - [x] one is the interactive workbook without coding
- [x] Test binder functionality
- [x] Publish new QSDsan/EXPOsan with the workshop needed updates
- [x] Make and test the live word cloud tool
- [x] Upload workshop slides
- [x] Send a QSDsan mass email about the workshop

**Comment by yalinli2** [comment]
All done!
